apiVersion: v1
kind: ConfigMap
metadata:
  name: basket-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_HTTP_PORTS: "8080"
  ASPNETCORE_HTTPS_PORTS: "8081"
  GrpcSettings__DiscountUrl: "http://discount-grpc:8080"


---
apiVersion: v1
kind: Secret
metadata:
  name: basket-api-secret
type: Opaque
data:
  ConnectionStrings__Database: U2VydmVyPWJhc2tldGRiO1BvcnQ9NTQzMjtEYXRhYmFzZT1CYXNrZXREYjtVc2VyIElkPXBvc3RncmVzO1Bhc3N3b3JkPXBvc3RncmVzO0luY2x1ZGUgRXJyb3IgRGV0YWlsPXRydWU=
  MessageBroker__Host: YW1xcDovL21lc3NhZ2Vicm9rZXI6NTY3Mg==
  MessageBroker__UserName: Z3Vlc3Q=
  MessageBroker__Password: Z3Vlc3Q=
  JwtSettings__Issuer: Y3VzdG9tZXItYXBpLXNlcnZpY2U=
  JwtSettings__Audience: ZXNob3Atc2VydmljZXM=
  JwtSettings__Key: bXlzZWNyZXRrZXkxMjM0NW15c2VjcmV0a2V5MTIzNDU=


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api
  labels:
    app: basket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
      - name: basket-api
        image: gknikolic/basketapi:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: basket-api-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_HTTP_PORTS
          valueFrom:
            configMapKeyRef:
              name: basket-api-config
              key: ASPNETCORE_HTTP_PORTS
        - name: ASPNETCORE_HTTPS_PORTS
          valueFrom:
            configMapKeyRef:
              name: basket-api-config
              key: ASPNETCORE_HTTPS_PORTS
        - name: ConnectionStrings__Database
          valueFrom:
            secretKeyRef:
              name: basket-api-secret
              key: ConnectionStrings__Database
        - name: ConnectionStrings__Redis
          value: "distributedcache:6379"
        - name: GrpcSettings__DiscountUrl
          valueFrom:
            configMapKeyRef:
              name: basket-api-config
              key: GrpcSettings__DiscountUrl
        - name: MessageBroker__Host
          valueFrom:
            secretKeyRef:
              name: basket-api-secret
              key: MessageBroker__Host
        - name: MessageBroker__UserName
          valueFrom:
            secretKeyRef:
              name: basket-api-secret
              key: MessageBroker__UserName
        - name: MessageBroker__Password
          valueFrom:
            secretKeyRef:
              name: basket-api-secret
              key: MessageBroker__Password
        - name: JwtSettings__Issuer
          valueFrom:
            secretKeyRef:
              name: basket-api-secret
              key: JwtSettings__Issuer
        - name: JwtSettings__Audience
          valueFrom:
            secretKeyRef:
              name: basket-api-secret
              key: JwtSettings__Audience
        - name: JwtSettings__Key
          valueFrom:
            secretKeyRef:
              name: basket-api-secret
              key: JwtSettings__Key


---
apiVersion: v1
kind: Service
metadata:
  name: basket-api
spec:
  selector:
    app: basket-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
