apiVersion: v1
kind: ConfigMap
metadata:
  name: discount-grpc-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_HTTP_PORTS: "8080"
  ASPNETCORE_HTTPS_PORTS: "8081"


---
apiVersion: v1
kind: Secret
metadata:
  name: discount-grpc-secret
type: Opaque
data:
  ConnectionStrings__Database: RGF0YSBTb3VyY2U9ZGlzY291bnRkYg==
  JwtSettings__Issuer: Y3VzdG9tZXItYXBpLXNlcnZpY2U=
  JwtSettings__Audience: ZXNob3Atc2VydmljZXM=
  JwtSettings__Key: bXlzZWNyZXRrZXkxMjM0NW15c2VjcmV0a2V5MTIzNDU=


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-grpc
  labels:
    app: discount-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount-grpc
  template:
    metadata:
      labels:
        app: discount-grpc
    spec:
      containers:
      - name: discount-grpc
        image: gknikolic/discountgrpc:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: discount-grpc-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_HTTP_PORTS
          valueFrom:
            configMapKeyRef:
              name: discount-grpc-config
              key: ASPNETCORE_HTTP_PORTS
        - name: ASPNETCORE_HTTPS_PORTS
          valueFrom:
            configMapKeyRef:
              name: discount-grpc-config
              key: ASPNETCORE_HTTPS_PORTS
        - name: ConnectionStrings__Database
          valueFrom:
            secretKeyRef:
              name: discount-grpc-secret
              key: ConnectionStrings__Database
        - name: JwtSettings__Issuer
          valueFrom:
            secretKeyRef:
              name: discount-grpc-secret
              key: JwtSettings__Issuer
        - name: JwtSettings__Audience
          valueFrom:
            secretKeyRef:
              name: discount-grpc-secret
              key: JwtSettings__Audience
        - name: JwtSettings__Key
          valueFrom:
            secretKeyRef:
              name: discount-grpc-secret
              key: JwtSettings__Key


---
apiVersion: v1
kind: Service
metadata:
  name: discount-grpc
spec:
  selector:
    app: discount-grpc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
