
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering-api
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      containers:
      - name: ordering-api
        image: orderingapi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_HTTP_PORTS
          value: "8080"
        - name: ASPNETCORE_HTTPS_PORTS
          value: "8081"
        - name: ConnectionStrings__Database
          value: "Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True"
        - name: MessageBroker__Host
          value: "amqp://messagebroker:5672"
        - name: MessageBroker__UserName
          value: "guest"
        - name: MessageBroker__Password
          value: "guest"
        - name: FeatureManagement__OrderFullfilment
          value: "false"
        ports:
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
        - mountPath: /root/.microsoft/usersecrets
          name: user-secrets
          readOnly: true
        - mountPath: /root/.aspnet/https
          name: aspnet-https
          readOnly: true
      volumes:
      - name: user-secrets
        hostPath:
          path: /path/to/microsoft/usersecrets  # Update this path accordingly
      - name: aspnet-https
        hostPath:
          path: /path/to/aspnet/https  # Update this path accordingly
---
apiVersion: v1
kind: Service
metadata:
  name: ordering-api
spec:
  selector:
    app: ordering-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  - protocol: TCP
    port: 8081
    targetPort: 8081
